name: metagenomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - diamond
  - nextflow>=23.10.0
  - fastp
  - megahit
  - kraken2==2.1.3
  - bracken==2.6.0
  - krakentools
  - prodigal
  - metabat2
  - salmon>=1.0
  - pandas
  - samtools
  - multiqc
  - biopython
  - mmseqs2
  - pip
  - eggnog-mapper
  - pysam
  - scipy
  - matplotlib
  - pip:
    - git+https://github.com/tyjo/coptr
