name: metagenomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - diamond
  - nextflow>=24.04
  - fastp
  - megahit
  - kraken2==2.1.3
  - bracken
  - prodigal
  - salmon>=1.0
  - pandas
  - samtools
  - multiqc
  - biopython
  - mmseqs2
  - pip
  - pigz
  - minimap2>=2.28
  - metabat2>=2.17
  - eggnog-mapper
  - pysam
  - scipy
  - matplotlib
  - pip:
    - git+https://github.com/tyjo/coptr
