name: metagenomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - diamond
  - nextflow>=26.04
  - fastp
  - megahit
  - prodigal
  - salmon>=1.0
  - pandas
  - samtools
  - multiqc
  - biopython
  - mmseqs2
  - pip
  - pigz
  - eggnog-mapper
  - pysam
  - scipy
  - matplotlib
  - metaMDBG
  - fastplong
  - singlem
  - spades
  - pip:
    - git+https://github.com/tyjo/coptr
