name: model_builder
channels:
  - conda-forge
  - bioconda
  - default
dependencies:
  - python>=3.8
  - nextflow
  - diamond
  - cobra
  - pip
  - wheel
  - prodigal
  - pip:
    - carveme
    - memote
    - /home/isilon/users/o_diener/software/cplex/python/3.x/x86-64_linux/
