name: Check workflow definitions
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nf-core/setup-nextflow@v2
        with:
          version: latest-edge

      - name: Lint the pipelines
        run: |
            nextflow lint ${GITHUB_WORKSPACE}/*/*.nf